export const TYPES = {
  IProductRepository: Symbol.for('IProductRepository'),
  IProductService: Symbol.for('IProductService'),
  ProductModel: Symbol.for('ProductModel'),
  IOrderService: Symbol.for('IOrderService'),
  OrderRepository: Symbol.for('OrderRepository'),
  ProductFaceRepository: Symbol.for('ProductFaceRepository'),
  OrderModel: Symbol.for('OrderModel'),
  UserModel: Symbol.for('UserModel'),
  ILogger: Symbol.for('ILogger'),
  IDatabase: Symbol.for('IDatabase'),
  IAlgoliaService: Symbol.for('IAlgoliaService'),
  IDefaultAlgoliaConfig: Symbol.for('IDefaultAlgoliaConfig'),
  IZohoAuthService: Symbol.for('IZohoAuthService'),
  IZohoCrmService: Symbol.for('IZohoCrmService'),
  ILLMService: Symbol.for('ILLMService'),
  IFactGenerationService: Symbol.for('IFactGenerationService'),
  ProductFactModel: Symbol.for('ProductFactModel'),
  ContentSanitizer: Symbol.for('ContentSanitizer'),
};
